Added support on pdf preview and radiology error on feeding input for paid status and insurance also gepg ammendment
udsm-dhis2-lab/iCareConnect pull request #408
Opened 2024-07-26 16:13 UTC by iamgaspardev

2024-07-26 22:04 UTC, Moricembiaji commented
Thanks @Gaspar Giddson ***@***.***>


On Fri, 26 Jul 2024 at 19:13, iamgaspardev ***@***.***> wrote:

> ------------------------------
> You can view, comment on, or merge this pull request online at:
>
>   https://github.com/udsm-dhis2-lab/iCareConnect/pull/408
> Commit Summary
>
>    - e7a2745
>    <https://github.com/udsm-dhis2-lab/iCareConnect/pull/408/commits/e7a2745374a490d26583c7659edf0244034f237b>
>    omods error resolved
>    - d617c6c
>    <https://github.com/udsm-dhis2-lab/iCareConnect/pull/408/commits/d617c6c5a7ee0023cc67076457a1f3997bdb94e5>
>    added support on radiology remarks and allow paid to input and inssurance
>    - 9647572
>    <https://github.com/udsm-dhis2-lab/iCareConnect/pull/408/commits/9647572cfe29c9f0d4b7b5c9bd17d881759f9df1>
>    added support on the radiology page for user with paid status to add inputs
>    also remarks and also for those with insurance
>    - 1623835
>    <https://github.com/udsm-dhis2-lab/iCareConnect/pull/408/commits/1623835f2a30361d0d34feb118da206dbb590116>
>    added support on pdf preview to the doctor side
>    - 5a648f7
>    <https://github.com/udsm-dhis2-lab/iCareConnect/pull/408/commits/5a648f739f2c7d84001d3e7e9e05c9cfe942b82d>
>    added support on pdf preview to the doctor side
>    - da9c65f
>    <https://github.com/udsm-dhis2-lab/iCareConnect/pull/408/commits/da9c65fd351a9fae41fb8fa70476f4e649146723>
>    added support on pdf preview to the doctor side
>    - 396fa75
>    <https://github.com/udsm-dhis2-lab/iCareConnect/pull/408/commits/396fa7528b8f631446e85214e76172c20d8106e1>
>    added support to the document preview to a doctor
>    - 4d6f13f
>    <https://github.com/udsm-dhis2-lab/iCareConnect/pull/408/commits/4d6f13fa3cc2ecf554977c333e27cf73ad7c914c>
>    added support to the document preview to a doctor
>    - 8f42e6c
>    <https://github.com/udsm-dhis2-lab/iCareConnect/pull/408/commits/8f42e6c4fa38e6eca3ade3b83976dba083a621e9>
>    added support to the document preview to a doctor
>    - b5fda4e
>    <https://github.com/udsm-dhis2-lab/iCareConnect/pull/408/commits/b5fda4ee6c74158fd91e84c62a104e93ddea56bd>
>    added support on pdf preview and gepg and radiology
>    - f047932
>    <https://github.com/udsm-dhis2-lab/iCareConnect/pull/408/commits/f0479328ecdb89666f1630c09069b13d1550497f>
>    added support on pdf preview and gepg and radiology
>    - 105cd61
>    <https://github.com/udsm-dhis2-lab/iCareConnect/pull/408/commits/105cd612dbe26a49513078df1fc5d64f6258f641>
>    Added support to the radiology and gepg and pdf view
>    - aff08ce
>    <https://github.com/udsm-dhis2-lab/iCareConnect/pull/408/commits/aff08ce720e7e2586f65766fb6762036638cf8eb>
>    Added support to the radiology and gepg and pdf view
>
> File Changes
>
> (300 files <https://github.com/udsm-dhis2-lab/iCareConnect/pull/408/files>
> )
>
>    - *M* .gitignore
>    <https://github.com/udsm-dhis2-lab/iCareConnect/pull/408/files#diff-bc37d034bad564583790a46f19d807abfe519c5671395fd494d8cce506c42947>
>    (12)
>    - *M* docker/build-local.sh
>    <https://github.com/udsm-dhis2-lab/iCareConnect/pull/408/files#diff-0edc98b5e4fc9b5ba85f5cc3745c52578d8b2efc8b21aaaebbb985ae6f01fb42>
>    (3)
>    - *A* node_modules/.bin/color-support
>    <https://github.com/udsm-dhis2-lab/iCareConnect/pull/408/files#diff-73ef0f4d44c36a8da140de16fc84822154b28c690ddd426e065f2bfbf08c358a>
>    (1)
>    - *A* node_modules/.bin/mkdirp
>    <https://github.com/udsm-dhis2-lab/iCareConnect/pull/408/files#diff-792b9e064419de85a27bb32e20c08ccf47313fde80a017e8d3f81de614afd8d7>
>    (1)
>    - *A* node_modules/.bin/node-pre-gyp
>    <https://github.com/udsm-dhis2-lab/iCareConnect/pull/408/files#diff-c5f6e89954c98dc2c4bc4adbb7352ff133320671bb4bb74a5de0df732f6db2ff>
>    (1)
>    - *A* node_modules/.bin/nopt
>    <https://github.com/udsm-dhis2-lab/iCareConnect/pull/408/files#diff-1afda08d7d7e3dbf4edb184f954a5f0c09895ef8ef9ecb84210742095acc19e8>
>    (1)
>    - *A* node_modules/.bin/rimraf
>    <https://github.com/udsm-dhis2-lab/iCareConnect/pull/408/files#diff-eba050fca881ed8985e7260d57268ae19d3ba52b6a888f912f43ca7559b45e52>
>    (1)
>    - *A* node_modules/.bin/semver
>    <https://github.com/udsm-dhis2-lab/iCareConnect/pull/408/files#diff-ca525319fbbdf1e8210416bd5dd69362dfc53c7b760339aae167417ec02851b6>
>    (1)
>    - *A* node_modules/.package-lock.json
>    <https://github.com/udsm-dhis2-lab/iCareConnect/pull/408/files#diff-4a2a59625b3d0885b2b53ebeddf2ea1ef51d1842735cf3501e1e7212b89f0345>
>    (710)
>    - *A* ***@***.***/node-pre-gyp/.github/workflows/codeql.yml
>    <https://github.com/udsm-dhis2-lab/iCareConnect/pull/408/files#diff-92c84eff51cf0ef551e0b593f1207e6c04633a92d04cc65c7a4e33f0c3e0dd1a>
>    (74)
>    - *A* ***@***.***/node-pre-gyp/CHANGELOG.md
>    <https://github.com/udsm-dhis2-lab/iCareConnect/pull/408/files#diff-b3838fe132c85ce00abd227dddaba87f88037b9d72d2ac3b90fa0991351da194>
>    (510)
>    - *A* ***@***.***/node-pre-gyp/LICENSE
>    <https://github.com/udsm-dhis2-lab/iCareConnect/pull/408/files#diff-6699c041553a6827eef049bee708776027e7eba9b794b9d508f3a1ae99a620c4>
>    (27)
>    - *A* ***@***.***/node-pre-gyp/README.md
>    <https://github.com/udsm-dhis2-lab/iCareConnect/pull/408/files#diff-5a62ecb06dd0c97eb08ca5b509e5e1c836913605cb5a4dad0611fffe5da49bf4>
>    (742)
>    - *A* ***@***.***/node-pre-gyp/bin/node-pre-gyp
>    <https://github.com/udsm-dhis2-lab/iCareConnect/pull/408/files#diff-14f3f8649d259625142c9e26a3a8d7b9c99874227fcb6f9ca584c33697ff0c6c>
>    (4)
>    - *A* ***@***.***/node-pre-gyp/bin/node-pre-gyp.cmd
>    <https://github.com/udsm-dhis2-lab/iCareConnect/pull/408/files#diff-d7c4f40185c8fa93e32cfa6c50ef1da088fd23deef486a39190e40bc08d85b71>
>    (2)
>    - *A* ***@***.***/node-pre-gyp/contributing.md
>    <https://github.com/udsm-dhis2-lab/iCareConnect/pull/408/files#diff-2f9f67c59f222d642995bec53b6522fc2abbe279d8773f22f9f4186d6a394d2f>
>    (10)
>    - *A* ***@***.***/node-pre-gyp/lib/build.js
>    <https://github.com/udsm-dhis2-lab/iCareConnect/pull/408/files#diff-33cc6ce70270353e4452b9ec39ff15ac6aa05b3201cda1469a3786597afcaa82>
>    (51)
>    - *A* ***@***.***/node-pre-gyp/lib/clean.js
>    <https://github.com/udsm-dhis2-lab/iCareConnect/pull/408/files#diff-d39aaedff630051288c283523c15566d5e390736c29e9b16e617f95cf57b0dc6>
>    (31)
>    - *A* ***@***.***/node-pre-gyp/lib/configure.js
>    <https://github.com/udsm-dhis2-lab/iCareConnect/pull/408/files#diff-24ad3a661fbd75b458704ed59a845d4d4e01a3834fc8a101042fdffa58240052>
>    (52)
>    - *A* ***@***.***/node-pre-gyp/lib/info.js
>    <https://github.com/udsm-dhis2-lab/iCareConnect/pull/408/files#diff-01d702dfc687a5d7424b795c2ff94c55e78dff886d1c371119cccc5b82681b65>
>    (38)
>    - *A* ***@***.***/node-pre-gyp/lib/install.js
>    <https://github.com/udsm-dhis2-lab/iCareConnect/pull/408/files#diff-959f8218a6a3b88d9c24c2566f49a7521c5a6dc0680aea34b4db90005a66029e>
>    (235)
>    - *A* ***@***.***/node-pre-gyp/lib/main.js
>    <https://github.com/udsm-dhis2-lab/iCareConnect/pull/408/files#diff-7779d429a6284f5df7ebb3b98362dcb05b333f00ebaffb8af97e4fbc72d2bc46>
>    (125)
>    - *A* ***@***.***/node-pre-gyp/lib/node-pre-gyp.js
>    <https://github.com/udsm-dhis2-lab/iCareConnect/pull/408/files#diff-1089b7b523b981ea3597eaaeacf1aed62f412d5fb10aa6c782465d180de707ce>
>    (309)
>    - *A* ***@***.***/node-pre-gyp/lib/package.js
>    <https://github.com/udsm-dhis2-lab/iCareConnect/pull/408/files#diff-53048011cb19e057fd235630d37d7bd068aa75051a44e518a81b36eb0993ab4c>
>    (73)
>    - *A* ***@***.***/node-pre-gyp/lib/pre-binding.js
>    <https://github.com/udsm-dhis2-lab/iCareConnect/pull/408/files#diff-ed58e8040235361835cbf2ee74d1ec625f08d83ed0a618aafabae09b49119fc9>
>    (34)
>    - *A* ***@***.***/node-pre-gyp/lib/publish.js
>    <https://github.com/udsm-dhis2-lab/iCareConnect/pull/408/files#diff-d52cb8dbe2d4c41dda76a243c069c16624ff912ed5c93378ce71952db1028c50>
>    (81)
>    - *A* ***@***.***/node-pre-gyp/lib/rebuild.js
>    <https://github.com/udsm-dhis2-lab/iCareConn [...]

2024-07-31 06:31 UTC, josephatJ requested changes
Please address the comments first before i approve

2024-07-31 06:31 UTC, josephatJ commented on docker/build-local.sh
Seems you have changed the file to build local. This means it will fail to build

2024-07-31 06:31 UTC, josephatJ commented on package-lock.json
If this file is not within UI folder consider deleting it

2024-07-31 06:31 UTC, josephatJ commented on package.json
This is supposed to be deleted

2024-07-31 06:31 UTC, josephatJ commented on ui/src/app/modules/billing/components/bill-confirmation/bill-confirmation.component.ts
Please make sure you remove logs before going live

2024-07-31 06:31 UTC, josephatJ commented on ui/src/app/shared/dialogs/shared-pdf-preview/shared-pdf-preview.component.ts
Remove console logs before pushing

2024-07-31 07:00 UTC, Moricembiaji commented
@Gaspar Giddson ***@***.***> Please work on it immediately
so that I can test it today.

On Wed, 31 Jul 2024 at 09:31, Josephat Julius M ***@***.***>
wrote:

> ***@***.**** requested changes on this pull request.
>
> Please address the comments first before i approve
> ------------------------------
>
> On docker/build-local.sh
> <https://github.com/udsm-dhis2-lab/iCareConnect/pull/408#discussion_r1697966376>
> :
>
> Seems you have changed the file to build local. This means it will fail to
> build
> ------------------------------
>
> On package-lock.json
> <https://github.com/udsm-dhis2-lab/iCareConnect/pull/408#discussion_r1697968092>
> :
>
> If this file is not within UI folder consider deleting it
> ------------------------------
>
> On package.json
> <https://github.com/udsm-dhis2-lab/iCareConnect/pull/408#discussion_r1697968531>
> :
>
> This is supposed to be deleted
> ------------------------------
>
> On
> ui/src/app/modules/billing/components/bill-confirmation/bill-confirmation.component.ts
> <https://github.com/udsm-dhis2-lab/iCareConnect/pull/408#discussion_r1697969176>
> :
>
> Please make sure you remove logs before going live
> ------------------------------
>
> On
> ui/src/app/shared/dialogs/shared-pdf-preview/shared-pdf-preview.component.ts
> <https://github.com/udsm-dhis2-lab/iCareConnect/pull/408#discussion_r1697970401>
> :
>
> Remove console logs before pushing
>
> —
> Reply to this email directly, view it on GitHub
> <https://github.com/udsm-dhis2-lab/iCareConnect/pull/408#pullrequestreview-2209276770>,
> or unsubscribe
> <https://github.com/notifications/unsubscribe-auth/A2TLCLC5GZQFJ7R4RNQXKJ3ZPCAFLAVCNFSM6AAAAABLQZP3LCVHI2DSMVQWIX3LMV43YUDVNRWFEZLROVSXG5CSMV3GSZLXHMZDEMBZGI3TMNZXGA>
> .
> You are receiving this because you commented.Message ID:
> ***@***.***>
>

2024-07-31 09:22 UTC, josephatJ reviewed
Noted

2024-07-31 09:22 UTC, merged